import 'package:flutter/material.dart';
import '../models/housing.dart';

class HousingState extends ChangeNotifier {
  final List<Housing> _housings = [
    Housing(
      id: '1',
      name: '忠孝新生套房',
      city: '台北市',
      district: '大安區',
      nearbyStation: '忠孝新生',
      transportType: '腳踏車',
      commuteMinutes: 8,
      oneWayFare: 0,
      rent: 14500,
      size: 9,
      age: 20,
      floor: 4,
      hasPrivateBath: true,
      hasFurniture: true,
      hasAC: true,
      nearMRT: true,
      safetyScore: 85,
      lifeScore: 90,
    ),
    Housing(
      id: '2',
      name: '善導寺雅房',
      city: '台北市',
      district: '中正區',
      nearbyStation: '善導寺',
      transportType: '步行',
      commuteMinutes: 12,
      oneWayFare: 0,
      rent: 9500,
      size: 6,
      age: 30,
      floor: 3,
      hasPrivateBath: false,
      hasFurniture: true,
      hasAC: false,
      nearMRT: true,
      safetyScore: 80,
      lifeScore: 85,
    ),
    Housing(
      id: '3',
      name: '南京復興套房',
      city: '台北市',
      district: '松山區',
      nearbyStation: '南京復興',
      transportType: '捷運',
      commuteMinutes: 15,
      oneWayFare: 25,
      rent: 11000,
      size: 8,
      age: 18,
      floor: 5,
      hasPrivateBath: true,
      hasFurniture: true,
      hasAC: true,
      nearMRT: true,
      safetyScore: 82,
      lifeScore: 88,
    ),
    Housing(
      id: '4',
      name: '台北橋套房',
      city: '新北市',
      district: '三重區',
      nearbyStation: '台北橋',
      transportType: '捷運',
      commuteMinutes: 18,
      oneWayFare: 25,
      rent: 7500,
      size: 8,
      age: 22,
      floor: 2,
      hasPrivateBath: true,
      hasFurniture: false,
      hasAC: true,
      nearMRT: true,
      safetyScore: 72,
      lifeScore: 78,
    ),
    Housing(
      id: '5',
      name: '頂溪雅房',
      city: '新北市',
      district: '永和區',
      nearbyStation: '頂溪',
      transportType: '捷運',
      commuteMinutes: 22,
      oneWayFare: 25,
      rent: 6500,
      size: 5,
      age: 28,
      floor: 3,
      hasPrivateBath: false,
      hasFurniture: true,
      hasAC: false,
      nearMRT: true,
      safetyScore: 75,
      lifeScore: 75,
    ),
    Housing(
      id: '6',
      name: '板橋小套房',
      city: '新北市',
      district: '板橋區',
      nearbyStation: '板橋',
      transportType: '捷運',
      commuteMinutes: 30,
      oneWayFare: 35,
      rent: 6000,
      size: 7,
      age: 15,
      floor: 4,
      hasPrivateBath: true,
      hasFurniture: false,
      hasAC: true,
      nearMRT: true,
      safetyScore: 78,
      lifeScore: 80,
    ),
    Housing(
      id: '7',
      name: '景安套房',
      city: '新北市',
      district: '中和區',
      nearbyStation: '景安',
      transportType: '捷運',
      commuteMinutes: 28,
      oneWayFare: 30,
      rent: 6800,
      size: 8,
      age: 20,
      floor: 3,
      hasPrivateBath: true,
      hasFurniture: true,
      hasAC: true,
      nearMRT: true,
      safetyScore: 76,
      lifeScore: 78,
    ),
    Housing(
      id: '8',
      name: '西門雅房',
      city: '台北市',
      district: '萬華區',
      nearbyStation: '西門',
      transportType: '公車',
      commuteMinutes: 20,
      oneWayFare: 15,
      rent: 8000,
      size: 6,
      age: 35,
      floor: 2,
      hasPrivateBath: false,
      hasFurniture: true,
      hasAC: false,
      nearMRT: true,
      safetyScore: 70,
      lifeScore: 85,
    ),
  ];

  List<Housing> get housings => List.unmodifiable(_housings);

  void addHousing(Housing h) {
    _housings.add(h);
    notifyListeners();
  }

  void updateHousing(Housing h) {
    final i = _housings.indexWhere((x) => x.id == h.id);
    if (i != -1) {
      _housings[i] = h;
      notifyListeners();
    }
  }

  void removeHousing(String id) {
    _housings.removeWhere((x) => x.id == id);
    notifyListeners();
  }
}